### ISSUE TITLE
Help Wanted - adding more log Handlers

### ISSUE THREAD

**Issue by joeybloggs** [go-playground/log#1]
Hello All,

I could definitely use some help adding even more log Handlers for other services such as Graylog, Email, InfluxDB, ElasticSearch... list goes on.

Thanks in Advance for anyone whom can help! 👍

**Comment by hartfordfive** [comment]
@joeybloggs I'll get a bit more familiar with this library and then I should be able to help with some of the handlers.  I will start with ElastisSearch and probably a generic HTTP handler, which could allow you to send directly to Logstash.

**Comment by joeybloggs** [comment]
fantastic! @hartfordfive , grateful for any help 👍
