### ISSUE TITLE
UTC time

### ISSUE THREAD

**Issue by sebastianwebber** [go-playground/log#11]
Hi there!

There is any particular reason to force UTC timestamp?

Regards,
Sebastian

**Comment by joeybloggs** [comment]
@sebastianwebber no, other than logs should be in UTC to avoid time zone and dst issues; but your just converting it to UTC isn’t good enough, the machines time zone must be set accordingly.

I was revamping this library to allow preset values, I’ll remove the explicit UTC conversation at that time :)

**Comment by sebastianwebber** [comment]
Hi @joeybloggs,

I do that. I create a custom handler and inside it, i convert the timestamp to a new locale (`America/Sao_Paulo` in my case).

I use something like this:

```golang
b.WriteString(e.Timestamp.In(loc).Format(defaultFormat))
```

Thanks for your help.
