### ISSUE TITLE
Unable to remove handlers

### ISSUE THREAD

**Issue by Chiiruno** [go-playground/log#19]
`addHandlers` just keeps the handler there forever with no way to remove it or change it.
`removeHandlers` would be a great method for this.
Consider servers where you can change the error email live, the only thing you can do right now is change and restart the program.

**Comment by Chiiruno** [comment]
Alternatively, being able to change the contents within each handler freely would also work.

**Comment by joeybloggs** [comment]
@Chiiruno that is what I was going to suggest, that logic really does belong to each handler and how you wish to operate it.
