### ISSUE TITLE
Ability to change or disable log levels

### ISSUE THREAD

**Issue by Chiiruno** [go-playground/log#24]
Being able to disable or change the log levels for a handler is important for projects which may rely on toggle-able features.

Related: [bakape/meguca#730](https://github.com/bakape/meguca/pull/730)

**Comment by joeybloggs** [comment]
I had plans for this sort of thing in the future, I guess the timetable just got pushed up though.

this may take me a bit to get to, please be patient.

**Comment by Chiiruno** [comment]
Thank you very much!

**Comment by joeybloggs** [comment]
Hey @Chiiruno I've finally got around to making this functionality available in [Release v6.4.0](https://github.com/go-playground/log/releases/tag/v6.4.0)

it not supports Go modules and was upgraded to use the latest go-plyground/errors package

let me know how it goes 😄
