### ISSUE TITLE
cannot use syscall.Stdout as type int in argument to terminal.IsTerminal

### ISSUE THREAD

**Issue by cup** [go-playground/log#31]
~~~
$ go get -v github.com/go-playground/log
github.com/go-playground/log
# github.com/go-playground/log
C:\Users\Steven\go\src\github.com\go-playground\log\log.go:24:24: cannot use
syscall.Stdout (type syscall.Handle) as type int in argument to
terminal.IsTerminal
~~~

**Comment by deankarn** [comment]
@cup just to verify you are using Windows? and what version of Go are you using?

will try to get this fixed today.

**Comment by cup** [comment]
@deankarn at work now so cant answer fully

but i believe im using `go1.12.5.windows-amd64.zip`

i think all that needs to be done is wrap with int

~~~go
terminal.IsTerminal(int(os.Stdout.Fd()))
~~~

https://cup.github.io/autumn/stream/is-a-terminal

**Comment by deankarn** [comment]
resolved in https://github.com/go-playground/log/releases/tag/v7.0.1
