### ISSUE TITLE
Cannot use in a module based project

### ISSUE THREAD

**Issue by SinisterMinister** [go-playground/log#35]
Essentially, the `go.mod` definition is malformed and causes projects attempting to consume the module by importing the latest version using `import "github.com/go-playground/log/v7"`. Also, the sub-modules need to be updated to use the proper import path. Otherwise they will be importing the `v6.3.0` version of the module.

**Comment by SinisterMinister** [comment]
Refer to golang/go#31543 for more details.

**Comment by deankarn** [comment]
fixed in Release [v7.0.2](https://github.com/go-playground/log/releases/tag/v7.0.2)
