### ISSUE TITLE
Go playground issue

### ISSUE THREAD

**Issue by giteeup12** [go-playground/log#38]
it seems there is a problem with the Go playground- when I try to run this from the Golang tutorial https://go.dev/tour/flowcontrol/12 I get an error ("can't connect to server) but when I copy and paste the code to another playground window, it works. Also obviously the tutorial /playground environment is being changed by the development team - when will it be stable?

**Comment by deankarn** [comment]
Hey @giteeup12 I think there must be some confusion, the `go-playground` GitHub organization is not affiliated in any way with the Go development team.

This is my personal organization which I use to organize my Go open source work.

**Comment by giteeup12** [comment]
Thanks

Sorry- do you know who I can contact about a problem in the Go playground?

**Comment by deankarn** [comment]
Sorry @giteeup12 I do not know who to contact TBH

**Comment by giteeup12** [comment]
Ok thx

Jim
