### ISSUE TITLE
v8 How to turn off the default output

### ISSUE THREAD

**Issue by 4781121** [go-playground/log#49]
package main

import (
	"bytes"
	"fmt"

	"github.com/go-playground/log/v8"
)

type CustomHandler struct {
}

func (c *CustomHandler) Log(e log.Entry) {
	b := new(bytes.Buffer)
	b.Reset()
	b.WriteString(e.Message)
	fmt.Println("-------------------- " + b.String())
}

func main() {
	log.RedirectGoStdLog(true)
	cLog := new(CustomHandler)
	log.AddHandler(cLog, log.AllLevels...)
	log.Debug("debug")
	log.Info("info")
	log.Notice("notice")
	log.Warn("warn")
	log.Error("error")
	log.Alert("alert")
}

-----------------

2023-06-20T16:42:19.821153700+08:00  DEBUG debug
-------------------- debug
2023-06-20T16:42:19.827476000+08:00   INFO info
-------------------- info
2023-06-20T16:42:19.827989800+08:00 NOTICE notice
-------------------- notice
2023-06-20T16:42:19.829013000+08:00   WARN warn
-------------------- warn
2023-06-20T16:42:19.829522600+08:00  ERROR error
-------------------- error
2023-06-20T16:42:19.829522600+08:00  ALERT alert
-------------------- alert

----------------
**how to show**

-------------------- debug
-------------------- info
-------------------- notice
-------------------- warn
-------------------- error
-------------------- alert

**Comment by deankarn** [comment]
@4781121  adding the custom handler should remove the default here https://github.com/go-playground/log/blob/master/log.go#L172

I haven’t had a chance to run your example to verify but is this a complete example?

will try to look at it this week, strange as I know it’s been working.

**Comment by deankarn** [comment]
@4781121 this should be all corrected in this release now :) https://github.com/go-playground/log/releases/tag/v8.0.2
