### ISSUE TITLE
Sharing fields between entries

### ISSUE THREAD

**Issue by Perlence** [go-playground/log#8]
What is the recommended way to use one collection of fields to log multiple entries? The obvious way:

``` go
func respond(requestID string) {
    l := log.WithFields(
        log.F("requestID", requestID),
    )
    l.Info("Everything goes ok")
    l.Warn("Something's wrong")
}
```

But it's completely wrong because of the way the package works -- each time I call `WithFields(...)`, I get an Entry from pool, and when I call `Info(...)` or `Warn(...)` I put Entry back into pool. There's no guarantee that I get the same Entry next time I log with the same "context".

I tried to approach this problem from a different angle by aliasing a slice and implementing `LeveledLogger`, so I can mutate and copy fields as I like:

``` go
type Fields []log.Field

func (fs Fields) Info(v ...interface{}) {
    log.WithFields(fs...).Info(v...)
}

func (fs Fields) WithFields(other ...log.Field) log.LeveledLogger {
    return append(fs, other...)
}

...

func respond(requestID string) {
    l := Fields{
        log.F("requestID", requestID),
    }
    l.Info("Everything goes ok")
    l[:].WithFields(log.F("temperature", 100)).Warn("Something's wrong")
    l.Info("Back to normal") // no "temperature" field
}
```

I wonder if I missed something and there's a simpler solution.

**Comment by joeybloggs** [comment]
Hey @Perlence 

No you haven't missed anything, when I was designing, I wanted to make sure that `log` was safe to be called from multiple goroutines and if the Entry was reusable then a possibility exists that someone could call it from multiple goroutines and cause themselves problems.

I do however understand your scenario and could look into creating a Release option or function to tell the Entry not to put itself and fields back into the pool.

Would that be something you'd be interested in.?
eg.
```go
// Calling Release() releases the Entry and all fields from
// being managed by the package...
l := log.WithFields(...).Release()

l.Info(...)
```

**Comment by Perlence** [comment]
Thank you for reply. I really don't want to force you to make decisions that you'll regret later, so everything is completely up to you 😄

I think that while Release allows to log same fields multiple times, it cannot be used to add one-off fields, e.g. some error information, and then log an entry with initial fields, because WithFields adds fields in place. So there could be something like `(*Entry) CopyWithFields`. But I'd like to see one method that can be used either to fix fields for later use or to copy existing fields into a new Entry.

"Release" also doesn't sound too clear to me, kind of low level, for example I didn't know about entry pool before fields started to "leak" through to other entries when I used context multiple times.

**Comment by joeybloggs** [comment]
Thanks for the ideas, let me think about how and if I could achieve this.

CopyWithFields() does seem like a good solution!

It may take me a bit to get to this as I'm adding new things to some of my other packages also, but I will get to this :smile:

**Comment by sebastianwebber** [comment]
@joeybloggs do you need help to implement this feature?

[]'s

**Comment by joeybloggs** [comment]
Hey @sebastianwebber I think I’ve got most of it done already in a local branch, just finalizing how I want to do the stack trace stuff, I’ll let you know if I could use help with anything though :)

**Comment by sebastianwebber** [comment]
nice @joeybloggs 

For now, i'm using:

```
...
log := log.WithFields(log.F("key", "value"))

log.Info("bla")
...
```

**Comment by joeybloggs** [comment]
ok @sebastianwebber @Perlence I finally got around to updating this library and it now supports sharing fields between entries!

sorry for how long it took, just be so busy with....everything.
